### ISSUE TITLE
Implement Error Codes to Extract Shorelines

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#125]
## Error Codes for Extract Shoreline Failures
1. Create a system to match an error code to a reason for why shoreline extraction failed
2. Identify the possible causes of shoreline extraction failure
3. Choose a file type, maybe a CSV, to store the name of a file, the error code and more
4. Optional display an optional status for the ROI ID that didn't successfully extract shorelines

![image](https://user-images.githubusercontent.com/61564689/231888054-325f48ef-6861-4762-b136-63deae853741.png)

**Comment by 2320sharon** [comment]
We might be able to implement a MVP of this idea for V1. This is from #146 

> Thank you! I think I'll sketch out an idea for how to implement this type of error messaging system.
> @dbuscombe-usgs what do you think of implementing error messages like these for extract shorelines?
> 
> Venus, do you think it would be helpful to have the error message say something like: "85% failed to not enough sand in reference shoreline buffer and 15% failed due to too many clouds in imagery" My reasoning is that each of the shorelines could fail to extract for different reasons, but we could summarize why groups of shorelines failed to extract so the user knows whats going on
> 
> Depending on the most common error message received some recommendations on how to solve the problem could be provided.
> For instance, with this one we could recommend the user to check their segmentations then increase the reference shoreline buffer size.

**Comment by 2320sharon** [comment]
Given that we now have users for coastseg I think we should implement error codes in V1 so users know what to try if shorelines fail to extract
@dbuscombe-usgs

**Comment by dbuscombe-usgs** [comment]
As discussed this morning, this is still a V2 feature. The order of progress should be, in my opinion:

1. finish implementing the zoo model shoreline extraction
2. then do some research on what error codes we could generate that would be useful/informative
3. then implement the method for the zoo model shoreline extraction. This should be easier, because there are fewer hyperparameters
4. if, and only if, the method proves useful, we could start tackling implementation for the coastsat method. There are more hyperparameters to keep track of, so may be more tricky

Ideally, each error code would come with an identifiable action. For example, a specific recommendation for the user to look at adjusting settings.

**Comment by 2320sharon** [comment]
This issue has be resolved in coastseg 1.1.20 and coastsat_package>=0.1.37
