### ISSUE TITLE
zenodo release https://zenodo.org/record/7933015 missing files

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#159]
Add 

* sat4class_rgb_512_v5_segformer_fullmodel.json

**Comment by dbuscombe-usgs** [comment]
I checked that this file is present. The issue may have been related to a lack of a model v4. Closing, but feel free to reopen if the is really an issue

**Comment by 2320sharon** [comment]
This file doesn't appear to be missing since the json files [sat4class_rgb_512_v5_segformer.json](https://zenodo.org/record/7933015/files/sat4class_rgb_512_v5_segformer.json?download=1) and [sat4class_rgb_512_v5_modelcard.json](https://zenodo.org/record/7933015/files/sat4class_rgb_512_v5_modelcard.json?download=1) exist
