### ISSUE TITLE
Use cloud probability layer for each S2 scene (s2cloudless)

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#164]
GEE has provided a cloud probability layer for each S2 scene, based on s2cloudless.

CoastSat has implemented this to mask S3 clouds. So should we. 

See, in SDS_preprocess.py:

- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_preprocess.py#L218
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_preprocess.py#L250
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_preprocess.py#L350

and in SDS_download.py:
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_download.py#L98
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_download.py#L118
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_download.py#L191
- https://github.com/kvos/CoastSat/blob/d7c14e2de52f7a1d5256912eb0ac55aaf26bf86c/coastsat/SDS_download.py#L952

[GEE article](https://developers.google.com/earth-engine/tutorials/community/sentinel-2-s2cloudless) 
[s2cloudless benchmarking article](https://www.sciencedirect.com/science/article/pii/S0034425722001043?via%3Dihub)

**Comment by 2320sharon** [comment]
This issue sounds like it belongs in coastsat package. I'm going to move it there.

**Comment by 2320sharon** [comment]
- This issue was developed on branch issue/164. 
- This feature is now available in coastseg version `1.1.0.dev2` `pip install coastseg==1.1.0.dev2`
- `coastsat_package` version `0.1.21` contains S2 cloudless band as well as all the updated code and it has been updated to make it backwards compatible.

## ChangeLog
### CoastSeg
1. `filter_metadata`
  - backwards compatible with old S2 imagery
2. ` edit_metadata`
- backwards compatible with old S2 imagery

### CoastSat_package
1.` SDS_preprocess.read_bands`
- modified this function to be able to read bands from the new and old S2 imagery. New imagery contains 5 raster bands and old S2 imagery contains 4 raster bands
2. `SDS_download.get_metadata`
- writes the new field  `im_dimensions` to the metadata.txt
- optionally writes `im_quality` and  `im_dimensions` to file if they exist
3. `SDS_download.read_metadata_file`
- reads new field for im_width and im_height which are used to create `im_dimensions` in metadata.txt
- converts the metadata values to the correct data types and can read metadata files regardless if they contain `im_quality` and  `im_dimensions` or not.
4.  `SDS_download.retrieve_images`
- now reads for more quality flags from S2
- no longer saves `acc_georef` `1` for `PASSED` image quality for S2 imagery
- saves the new cloudless band for S2 imagery
