### ISSUE TITLE
Filter out small imagery?

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/CoastSeg#183]
Often, partial images are downloaded, which are subsamples of the ROI we requested

This is potentially problematic for 2 reasons;
1. the image segmentation algorithm is likely to fail on tiny subsets of ROI imagery
2. The partial images are unlikely to be useful for extensive shoreline extraction anyway, because more often than not, the portion of imagery capturing the shoreline region is absent

A rudimentary filter of non-modal image shapes was implemented here
https://github.com/Doodleverse/CoastSeg/issues/154

It reads in every image (could use Dask), and makes a list of image shapes. Non-modal shapes are thrown out. This would fail for short time-series of images, so a better approach would be as follows;

1. compute area of ROI (I think this is already done with existing coastseg implementation)
2. compute ROI of downloaded image (number of pixels x pixel size, e.g. 10m for S2, 15m for L7, L8, L9, and 30m for L5)
3. if the two numbers are not the same, throw the image out

**Comment by 2320sharon** [comment]
Move these files into a bad folder.
1. mkdir bad 
2. Find all the too small images
3. Move them to the bad folder

**Comment by 2320sharon** [comment]
Users want the controls for this to be a simple on/off switch that by default filters out imagery that's less than 80% of the expected ROI area. This control should be on by default.

Users are also interested in understanding how these partial images happen, maybe its a GEE clipping issue?

- [ ] Implement the new control

- [ ]  Identify a region that contains partial imagery and manually create a  GEE query to see if you get the same clipping issue.

- [ ] @dbuscombe-usgs check the source imagery to check if this issue is a result of the ROI being on the edge of the swath of image the plane flew through ( I can't remember the technical term for this)

![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/12a1de2f-f4c2-4423-851c-7b300929255a)

**Comment by 2320sharon** [comment]
This feature has been implemented in coastseg `1.1.0.dev5`.

## ChangeLog
1. Add a new checkbox located under settings that controls if filter images is set to on/off
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/cd2f378d-4c5b-491b-987d-7f80e408f120)

2. Modified the minimum default value for filtering the images to be 60% of the ROI area
3. Added new functions 
- filter_partial_images
- filter_images
- filter_images_by_roi
4. Added tests for the following functions
- filter_partial_images
- get_roi_area
- filter_images
- get_most_accurate_epsg
- convert_wgs_to_utm
- get_epsg_from_geometry
5. Went from 116 tests to 133 automated tests
### Installation
`pip install coastseg==1.1.0.dev5`
